name: DeepDarkWorld
version: 1.0.0
main: gidor.deepdarkgen.deepdarkgen
api-version: '1.21'
description: Custom world generator with full Deep Dark biome injection.
authors: [MrGidor]
depend: [Multiverse-Core]
